### ISSUE TITLE
Principio de responsabilidad única

### ISSUE THREAD

**Issue by hvillega99** [JoseLuisIc/sistemaControlMedico#1]
Una única clase se encarga de abstraer la información de paciente y unidad médica. Se podría crear una clase por cada elemento. 
![image](https://user-images.githubusercontent.com/66192354/88010500-9f267380-cada-11ea-99f9-293a01b16e2a.png)
![image](https://user-images.githubusercontent.com/66192354/88010512-a5b4eb00-cada-11ea-871d-2fe9f2221b85.png)

**Comment by JoseLuisIc** [comment]
Excelente amigo, se estará trabajando en futuras versiones
